power_data=read.table("globalpower.txt",header = TRUE)
par(mfrow = c(2,2))
plot(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Global_active_power), type = 'l',xlab="",ylab = "Golbal Active Power")
plot(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Voltage), type = 'l',xlab = "datetime",ylab = "Voltage")
plot(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Sub_metering_1), type = 'l',xlab = "",ylab = "Energy sub metering")
lines(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Sub_metering_2), type = 'l', col="red")
lines(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Sub_metering_3), type = 'l', col="blue")
legend(x="topright", legend=c("sub_metring_1","sub_metering_2","sub_metering_3"),col=c("black","red","blue"),lty = 1, cex=0.5)
plot(strptime(paste(power_data$Date, power_data$Time),format="%d/%m/%Y %H:%M:%S"),as.numeric(power_data$Global_reactive_power), type = 'l',xlab="",ylab = "Golbal_reactive_power")
dev.copy(png,'plot4.png')
dev.off()